### ISSUE TITLE
Wrong me if im correct, but the keyword 𐤏𐤂𐤋 meaning is to round, not the absolute value

### ISSUE THREAD

**Issue by aharonha** [elonlit/Genesis#11]
This means that the equivalent of 𐤏𐤂𐤋 should be round(n)

**Comment by DoviLilling** [comment]
+1
And 𐤏𐤂𐤋 should change to 𐤌𐤅𐤇𐤋𐤈 or 𐤏𐤌𐤇.

**Comment by elonlit** [comment]
I made the correction. There is no use for a rounding function hitherto because there are no decimals (unless you divide using gematria), so I did not include a rounding function.
