### ISSUE TITLE
God object

### ISSUE THREAD

**Issue by AbrahamSanders** [elonlit/Genesis#12]
Since Genesis is God's actual programming language, it should be fairly straightforward to create a [God object](https://en.wikipedia.org/wiki/God_object) (or, since Genesis is not object-oriented, a [God method](http://wiki.c2.com/?GodMethod)). I believe this would make a useful addition to the examples.

**Comment by tomyo** [comment]
What would god represent here?

**Comment by AbrahamSanders** [comment]
An all knowing, all-encompassing entity that does everything.

> Because this object holds so much data and requires so many methods, its role in the program becomes God-like (all-knowing and all-encompassing).

> A "God Method" is a method that does way too many processes in the system and has grown beyond all logic to become The Method That Does Everything.

**Comment by elonlit** [comment]
Interesting proposal... I can see how something like this could be accomplished in Genesis by a composition of subroutines (i.e. a subroutine that contains several other subroutines and a singular call to one of them, followed by a call to the containing "parent" subroutine in the main scope), but I'm not sure what these routines would plausibly do. If you are talking about the actual source code, then I guess it could be refactored into such a method. I will do some pondering.
